export const MCP_PROTOCOL_VERSION: "2025-06-18";
export const MAX_RESULT_BYTES: number;
export const MAX_RESULT_LINES: number;
export const DEFAULT_TIMEOUT_MS: number;
export const DEFAULT_HANDSHAKE_BUDGET_MS: number;

export interface McpTextContent {
  type: "text";
  text: string;
}

export interface McpImageContent {
  type: "image";
  data: string;
  mimeType: string;
}

export type PiContentBlock = McpTextContent | McpImageContent;

/** An upstream `tools/list` entry, passed through untouched. */
export interface McpToolDescriptor {
  name: string;
  title?: string;
  description?: string;
  inputSchema?: any;
  [key: string]: any;
}

export interface McpBridgeLogger {
  log(stage: string, data?: any): void;
  logError(stage: string, err: unknown): void;
}

export type McpBridgeLoggerFactory = (hookName: string, config?: any) => McpBridgeLogger;

/**
 * The proxy handle returned by the shared core, described structurally:
 * `shared/mcp-proxy-core.mjs` is generated by sync.mjs and ships no
 * declarations, so this file must not `import type` from it.
 */
export interface McpProxyHandle {
  handleMessage(message: any): Promise<void>;
  closeSession(): Promise<void>;
  parseSseMessages?(text: string): any[];
  start?(): { close(): Promise<void> | void };
}

export interface McpBridgeState {
  /** True once initialize + tools/list have succeeded. */
  connected: boolean;
  closed: boolean;
  /** The last handshake failure, human-readable and complete. */
  error: string | null;
  /** Upstream descriptors; empty whenever the handshake has not succeeded. */
  tools: McpToolDescriptor[];
  /** Frames carrying a null id (-32600 / -32700): they settle no request. */
  stray: any[];
}

export interface McpBridgeCallResult {
  content: PiContentBlock[];
  details: {
    tool: string;
    structuredContent?: any;
    truncated: boolean;
  };
}

export interface McpBridgeOptions {
  /** Re-resolves the proxy config; the core re-invokes it on credential changes. */
  readConfig: () => any;
  loggerFactory?: McpBridgeLoggerFactory;
  fetchImpl?: (input: any, init?: any) => Promise<any>;
  clientInfo?: { name?: string; version?: string };
  /** Overrides the config's `timeoutMs`; the backstop is this plus 5000ms. */
  timeoutMs?: number;
}

export interface McpBridge {
  /** Handshakes once on a single shared deadline. Never rejects. */
  connect(budgetMs?: number): Promise<McpBridgeState>;
  callTool(
    name: string,
    args?: any,
    options?: { signal?: AbortSignal },
  ): Promise<McpBridgeCallResult>;
  close(): Promise<void>;
  readonly state: McpBridgeState;
  readonly proxy: McpProxyHandle;
}

export function createMcpBridge(options: McpBridgeOptions): McpBridge;

export function toPiParameters(inputSchema: any): Record<string, any>;
export function mcpContentToPi(result: any): PiContentBlock[];
export function joinText(blocks: any[]): string;
export function truncateText(
  text: string,
  options?: { maxBytes?: number; maxLines?: number },
): { text: string; truncated: boolean };
export function truncationHint(
  toolName: string,
  options?: { maxBytes?: number; maxLines?: number },
): string;
